#!/bin/bash
git fetch --prune

for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/ | grep -v '^main$'); do
    if ! git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
        echo "Deleting local branch '$branch' as it no longer exists on origin"
        git branch -D "$branch"
    fi
done